# Generated by Django 3.0.2 on 2020-01-13 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=5)),
                ('phone_number', models.IntegerField(default=0)),
                ('admin_user', models.BooleanField(default=False)),
                ('dob', models.DateField(default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('sex', models.CharField(max_length=10)),
                ('bio', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('pincode', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
