# Generated by Django 3.0.2 on 2020-01-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20200114_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
